# iOS CircleCI 2.0 configuration file
#
version: 2
jobs:
  build-and-test:
    macos:
      xcode: "10.0.0"
    working_directory: /Users/distiller/project
    environment:
      FL_OUTPUT_DIR: /Users/distiller/project/output

    steps:
      - checkout
      - run:
          name: Set Ruby version
          command: echo "ruby-2.4" > ~/.ruby-version
      - run: bundle install
      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-darwin-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run:
          name: Code Climate pre-build
          command: ./cc-test-reporter before-build
      - run:
          name: Build and run tests
          command: fastlane scan --code_coverage --output_directory output/scan
          environment:
            SCAN_DEVICE: iPhone X
            SCAN_SCHEME: WWLayout
      # Create cobertura.xml for Code Climate
      - run:
          name: Generate test coverage XML
          command: slather coverage
      - run:
          name: Generate test coverage HTML
          command: slather coverage --html --output-directory output/slather
      - run:
          name: Code Climate post-build
          command: ./cc-test-reporter after-build --debug --coverage-input-type cobertura --exit-code $?
      - store_artifacts:
          path: /Users/distiller/project/output
      - store_test_results:
          path: /Users/distiller/project/output

workflows:
  version: 2
  build-test:
    jobs:
      - build-and-test
