name: WW-Layout

on: 
 workflow_dispatch:
 
jobs:
  unit-test-4:
    runs-on: macos-11
    strategy:
     matrix:
      xcode-version: [13.2, 12.5.1]
    
    steps:
#       - name: checkout
#         uses: actions/checkout@v2  
      
#       - name: Pod update
#         run: bundle update fastlane         gem install fastlane

        
      - name: Install dependencies in Gemfile
        run: |
         xcbeautify --version
      
#       - name:  Unit Tests, using Swift ${{ matrix.swift-version }}
#         run: fastlane scan --devices "iPhone 8","iPhone 11"
#         env:
#          DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode-version }}.app
