name: WW-Layout

on: 
 workflow_dispatch:
 
jobs:
  unit-test-4:
    runs-on: macos-11
    strategy:
     matrix:
      xcode-version: [13.2, 12.5.1]
    env:
     DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode-version }}.app
    
    steps:
      - name: checkout
        uses: actions/checkout@v2  
        with: 
          repository: "ww-tech/wwlayout"
          ref: develop
          ssh-key: ${{ secrets.ssh_ww }}
          
      - name: Install dependencies in Gemfile
        run: bundle install 
      
      - name:  Unit Tests, using Swift 4.0
        run: |
          bundle exec fastlane scan \
                        --device "iPhone SE" \
                        --xcargs "SWIFT_VERSION=4.0" \
                        --code_coverage \
                        --output_directory output/scan 
      
      - name:  Unit Tests, using Swift 4.2
        run: |
          bundle exec fastlane scan \
                        --device "iPhone 8" \
                        --xcargs "SWIFT_VERSION=4.2" \
                        --code_coverage \
                        --output_directory output/scan
  
