name: WW-Layout

on: 
 pull_request:
 workflow_dispatch:
  
 
jobs:
  unit-test:
    runs-on: macos-11
    strategy:
     matrix:
      xcode-version: [13.2, 12.5.1]
    
    steps:
      - name: checkout
        uses: actions/checkout@v2  
      
      - name: Install dependencies in Gemfile
        run: gem install fastlane
      
      - name:  Unit Tests, using Xcode ${{ matrix.xcode-version }}
        run: fastlane scan --devices "iPhone 8,iPhone 11"
        env:
         DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode-version }}.app
  
  build-example:
    runs-on: macos-11
    steps:
      - name: checkout
        uses: actions/checkout@v2  
        
      - name: Build example (test spm)
        working-directory: WWLayoutExample/WWLayoutTV
        run: | 
          xcodebuild build \
           -project "WWLayoutTV.xcodeproj" \
           -scheme "WWLayoutTV" \
           -destination "platform=tvOS Simulator,name=Apple TV"
