name: WW-Layout

on: 
 workflow_dispatch:
 
jobs:
  unit-test-4:
    runs-on: macos-11
    strategy:
     matrix:
      xcode-version: [13.2, 12.5.1]
    
    steps:
      - name: checkout
        uses: actions/checkout@v2  
        with: 
          repository: "ww-tech/wwlayout"
          ref: develop
          ssh-key: ${{ secrets.ssh_ww }}
          
      - name: Install dependencies in Gemfile
        run: gem install fastlane
      
      - name:  Unit Tests, using Swift ${{ matrix.swift-version }}
        run: |
          fastlane scan \
            --device "iPhone SE" \
            --code_coverage \
            --output_directory output/scan 
        env:
         DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode-version }}.app
